#!/bin/sh

filename=$1
target="$(dirname "${filename}")/../pdf"
outputFile="$(basename "$filename").pdf"
mkdir -p "$target"
pandoc --pdf-engine=xelatex --wrap=preserve -o "$target/$outputFile" "$filename" &
