#!/bin/bash
extern=VGA1
if xrandr | grep "$extern disconnected"; then
	xrandr --output LVDS1 --off
	xrandr --output VGA1 --output DP2
	xrandr --output VGA1 --left-of DP2
else
	xrandr --output VGA1 --off
	xrandr --output DP2 --off
	xrandr --output LVDS1 --auto
fi
