#!/bin/bash
tmux new-session -s 'workin' -d -x "$(tput cols)" -y "$(tput lines)"
tmux split-window -v -p 20
tmux send-keys -t 2 "docker-compose up --build"
tmux split-window -h -p 40
tmux send-keys -t 3 "sudo dockerd" Enter
tmux select-pane -t 1
tmux split-window -h
tmux select-pane -t 1
tmux send-keys -t 1 "vfzf" Enter
tmux send-keys -t 2 "vfzf" Enter
tmux select-pane -t 2
tmux attach-session -t 'workin'
