#!/bin/bash
function play {
	mpc clear
	mpc load "$1"
	mpc shuffle
	mpc play
}
cmds="\
vibe	play lofi
cozy	play cozy
sniff	play sniff
ambient		play ambient
"
choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2,3-`
