#!/bin/bash
if ! grep -qs '/mnt/SSD ' /proc/mounts; then
	sudo mount /dev/sda1 /mnt/SSD
fi

cd /mnt/SSD/vids || exit 1


find /mnt/SSD/vids -name ".url" -print0 | while read -r -d $'\0' file
do
	cd "$( dirname "$file")" || exit 1
	youtube-dl -f best -ciw -o "%(title)s.%(ext)s" -v "$(cat .url)"
done

rsync -r /home/elamd/readz /mnt/SSD
